name: Build pull requests
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: 'Setting up node'
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npm run build --workspaces --if-present
      - run: npm run test:unit --workspaces --if-present
      - run: npm run test:integration --workspaces --if-present
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: packages/examples/project-a/playwright-report/
          retention-days: 30
